### ISSUE TITLE
lightweight MN-3 / permissionless trial network - a3p on akash without well-known keys?

### ISSUE THREAD

**Issue by dckc** [agoric-labs/ag-power-tools#23]
I have thought about putting `contractStarter` on devnet, but it increases the risk that devnet would get messed up and have to be restarted. So I'm thinking about options that I can deploy without putting any burden on Agoric Engineering.

@tgrecojs shared a [recipe for a3p on the akash console](https://discord.com/channels/585576150827532298/1197240838070214727/1197748442777272390) (copied below). I wondered about using it as a quick shared network. It works great, but the resulting node's key is published in the a3p image, so anybody else can mess with it. Maybe that's not a problem for this scenario? But it would be cool to have an [akash template](https://deploy.cloudmos.io/templates) for a reasonably secure Agoric node.

cc @0xpatrickdev 

```yml
---
version: "2.0"
services:
  node:
    image: ghcr.io/agoric/agoric-3-proposals:main
    expose:
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 26656
        as: 26656
        proto: tcp
        to:
          - global: true
      - port: 1317
        as: 1317
        to:
          - global: true
    env:
      - DEST=1
      - DEBUG='SwingSet:ls,SwingSet:vat'
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 10Gi
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  node:
    dcloud:
      profile: node
      count: 1
```
